#!/bin/bash

set -eu

function retry()
{
    local n=0
    local try=$1
    local cmd="${@: 2}"
    [[ $# -le 1 ]] && {
    echo "Usage $0 <retry_number> <Command>"; }
    until [[ $n -ge $try ]]
    do
        $cmd && break || {
            echo "Command Fail.."
            ((n++))
            echo "retry $n ::"
            sleep 1;
            }
    done
}

install-packages git build-essential ruby ruby-dev libxml2-dev libsqlite3-dev libxslt1-dev libpq-dev libmysqlclient-dev quota cmake unzip

# install spiff
wget https://github.com/cloudfoundry-incubator/spiff/releases/download/v1.0.3/spiff_linux_amd64.zip -O /tmp/spiff_linux_amd64.zip
unzip /tmp/spiff_linux_amd64.zip -d /usr/local/bin/
rm /tmp/spiff_linux_amd64.zip

# install bosh_cli
gem install bundler bosh_cli --no-ri --no-rdoc

# prepare repos
mkdir /root/workspace
# CF
cd /root/workspace
git clone https://github.com/cloudfoundry/cf-release
cd /root/workspace/cf-release
# checkout to release-207
#git reset --hard afbe01cecc67fc4fe45a1a7cfc774fc2baa25d6c
git checkout v207
# update
git submodule sync
git submodule foreach --recursive 'git submodule sync; git clean -d --force --force'
git submodule update --init --recursive --force
git clean -ffd
# remove buildpacks
cat << EOF > /root/workspace/remove-cf-buildpacks.patch
diff --git a/config/blobs.yml b/config/blobs.yml
index c048acc..fc6c0b3 100644
--- a/config/blobs.yml
+++ b/config/blobs.yml
@@ -115,32 +115,3 @@ consul/consul_0.5.0_linux_amd64.zip:
   object_id: 3e6c1e47-95a5-45ef-aeec-2cb4cc4c529a
   sha: 00e4c6e9ff2fb326d3b586fd86c3037f3b7e0974
   size: 4669655
-go-buildpack/go_buildpack-cached-v1.2.0.zip:
-  object_id: da609e02-aec5-4d54-93bc-86ca0b44eed7
-  sha: e58788c873ddbecd641532f32ce4d535b2a79f81
-  size: 663443569
-python-buildpack/python_buildpack-cached-v1.2.0.zip:
-  object_id: 3e8561a1-7cdc-45c2-9eff-b8d49ebc4e88
-  sha: 2ca4545ab99ac2a2e430f58fe1ec55fe6b96a7b3
-  size: 685706721
-ruby-buildpack/ruby_buildpack-cached-v1.3.0.zip:
-  object_id: 3d8d4bfc-91b2-419b-857d-9f26e31340bd
-  sha: 5dde3ea0e15908554eaa5b12df38652436c469b5
-  size: 966348817
-php-buildpack/php_buildpack-offline-v3.1.0.zip:
-  object_id: b817bdc3-4765-423c-aebd-195b980550a3
-  sha: 9bb6c36e13976288c62794f8dcb06965ef898033
-  size: 1089981446
-nodejs-buildpack/nodejs_buildpack-cached-v1.2.1.zip:
-  object_id: 21a8eb83-97b9-49cd-ba57-bd2cca1f9133
-  sha: !binary |-
-    OGM1MzQwNTdmYzFmZTBjY2JkZmE1NTQ3YzI1ZjMwYWQ3OWRkMzY4ZA==
-  size: 437119230
-java-buildpack/java-buildpack-offline-v3.0.zip:
-  object_id: 8fe6e89a-aa63-4119-8fd0-23715820f31d
-  sha: a300c3fca530dc16345dbd6feb26b13897d05265
-  size: 324816174
-java-buildpack/java-buildpack-v3.0.zip:
-  object_id: 34bff29b-9ec3-42aa-891f-db301f7f978d
-  sha: 177715b012505051d14611bf706f0ebe50cc55f0
-  size: 150091
diff --git a/jobs/cloud_controller_ng/spec b/jobs/cloud_controller_ng/spec
index 82a4545..90281eb 100644
--- a/jobs/cloud_controller_ng/spec
+++ b/jobs/cloud_controller_ng/spec
@@ -29,13 +29,6 @@ packages:
   - libpq
   - mysqlclient
   - ruby-2.1.4
-  - buildpack_java
-  - buildpack_java_offline
-  - buildpack_ruby
-  - buildpack_nodejs
-  - buildpack_go
-  - buildpack_python
-  - buildpack_php
 
 properties:
   ssl.skip_cert_verify:
EOF
patch -p1 < /root/workspace/remove-cf-buildpacks.patch
rm -f /root/workspace/remove-cf-buildpacks.patch
rm -rf packages/buildpack_*

# Diego
cd /root/workspace
git clone https://github.com/cloudfoundry-incubator/diego-release
cd /root/workspace/diego-release
# reset to release 0.1099
git reset --hard bbdd0d01a2bafb2f7772a0f088262858bccd4620
git submodule foreach --recursive git submodule sync && git submodule update --init --recursive
git submodule sync --recursive && git submodule foreach --recursive git submodule sync  && git submodule update --init --recursive

# generate manifests
echo "director_uuid: __director_uuid__" > /root/workspace/director.yml
cd /root/workspace/cf-release
./generate_deployment_manifest warden \
  /root/workspace/director.yml \
  /root/workspace/diego-release/stubs-for-cf-release/enable_diego_docker_in_cc.yml \
  /root/workspace/diego-release/stubs-for-cf-release/enable_consul_with_cf.yml \
  > /root/workspace/cf.yml
cd ~/workspace/diego-release
./scripts/generate-deployment-manifest \
    /root/workspace/director.yml \
    manifest-generation/bosh-lite-stubs/property-overrides.yml \
    manifest-generation/bosh-lite-stubs/instance-count-overrides.yml \
    manifest-generation/bosh-lite-stubs/persistent-disk-overrides.yml \
    manifest-generation/bosh-lite-stubs/iaas-settings.yml \
    manifest-generation/bosh-lite-stubs/additional-jobs.yml \
    /root/workspace \
    > /root/workspace/diego.yml
rm /root/workspace/director.yml

# create cf release file
cd /root/workspace/cf-release
retry 3 bosh -n create release --force --with-tarball
mv dev_releases/cf/cf-207+dev.1.tgz /root/workspace/cf-release.tgz

# create diego release file
cd /root/workspace/diego-release
retry 3 bosh -n create release --force --with-tarball
mv dev_releases/diego/diego-0.1099.0+dev.1.tgz /root/workspace/diego-release.tgz

# cleanup
rm -rf /root/workspace/cf-release
rm -rf /root/workspace/diego-release
rm -rf /root/.bosh

