<?php
  $sugar_config_si = array (
    'setup_db_host_name' => '%%DB_HOST%%',
    'setup_db_database_name' => '%%DB_NAME%%',
    'setup_db_drop_tables' => true,
    'setup_db_create_database' => true,
    'setup_site_admin_user_name' => '%%ADMIN_NAME%%',
    'setup_site_admin_password' => '%%ADMIN_PASSWORD%%',
    'setup_db_create_sugarsales_user' => false,
    'setup_db_admin_user_name' => '%%DB_USER%%',
    'setup_db_admin_password' => '%%DB_PASSWORD%%',
    'setup_site_url' => 'http://%%HOST%%/Sugar',
    'dbUSRData' => 'provide',
    'setup_db_type' => 'mysql',
    'setup_system_name' => 'SugarCRM',
    'default_currency_iso4217' => 'USD',
    'default_currency_name' => 'US Dollars',
    'default_currency_significant_digits' => '2',
    'default_date_format' => 'm/d/Y',
    'default_time_format' => 'h:ia',
    'default_decimal_seperator' => '.',
    'default_export_charset' => 'UTF-8',
    'default_language' => 'en_us',
    'default_locale_name_format' => 's f l',
    'default_number_grouping_seperator' => ',',
    'export_delimiter' => ',',
    'demoData' => '%%DEMO_DATA%%',
    'setup_site_sugarbeet_anonymous_stats' => '1',
    'setup_site_sugarbeet_automatic_checks' => '1',
    'setup_site_specify_guid' => '0',
    'setup_site_guid' => 'auto',
    );
?>
