#!/bin/bash

set -eu

os=$(uname)
dist_name='Unknown'

if [ "${os}" = "Linux" ] ; then
    if [ -f /etc/redhat-release ] ; then
        dist_name=$(cat /etc/redhat-release |sed s/\ release.*//)
    elif [ -f /etc/SuSE-release ] ; then
        dist_name='SuSe'
    elif [ -f /etc/lsb-release ]; then
        dist=$(cat /etc/lsb-release | grep '^DISTRIB_ID' | awk -F=  '{ print $2 }')
    fi
fi

dist_name=$(lowercase $dist_name)

if [ "${dist_name}" == 'ubuntu' ]; then
    if [ -e /usr/lib/apt/methods/https ]; then
        apt-get update
        apt-get install apt-transport-https
    fi
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
    echo "deb https://get.docker.com/ubuntu docker main" > /etc/apt/sources.list.d/docker.list
    apt-get update
    apt-get -y install lxc-docker=1.6.2
else
    install-packages curl
    curl -sSL https://get.docker.com/ | sh
fi
